### ISSUE TITLE
Team Activity - Excel List

### ISSUE THREAD

**Issue by AndreiP33** [FutureTechIonLuca/FutureRobot#6]
Who? : Bucevschi Vladut
Why? : For organization of tasks in the team
Dedline: 16.09.2022  -  20:00

**Comment by Vlad20405** [comment]
>

[ActivitateFutureTech.xlsx](https://github.com/FutureTechIonLuca/FutureRobot/files/9585281/ActivitateFutureTech.xlsx)

**Comment by AndreiP33** [comment]
Foarte bine, multumim!
